language: python

sudo: false  # use container based build

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install: 
  - pip install .
  - pip install nose

script: 
  - cd tests
  - nosetests
