# This GHA runs the compiler for our JOSS paper draft
# this action will also live temporarily in the main branch
# so that we can actually run it on the joss_paper branch, but it will be
# decativated on main, and it will run only on joss_paper branch, triggered by push

---
name: JOSS Draft PDF
on:
  push:
    branches:
      #  - main  # this will be deactivated after a first (unsuccessful) run
      - joss_paper

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: paper.md
      - name: Commit draft PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          # This should be the path to the paper within your repo.
          add: 'paper.pdf' # 'paper/*.pdf' to commit all PDFs in the paper directory
      - name: Upload paper.zip as GHA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: paper.pdf
